<style>
table {
	width:500px;
}
td, th {
	width : 200px;
	height :50px;
	border-bottom : 1px solid #ccc;
}
</style>
<div id="wrapper">
	<!-- end #header -->
	<div id="page">
       <section>
            <h1>Create a new entry</h1>
    
            <?php
            $this->entryForm->setAttribute('action', $this->url('add-request', ['id' => $idEmployee]));
            $this->entryForm->setAttribute('method', 'post');
            $this->entryForm->prepare();
            ?>
            <?php echo $this->form()->openTag($this->entryForm) ?>
        <dl>
            <dt><?php 
            $dateDebut = $this->entryForm->get('DateDebut');
            echo $this->formLabel($dateDebut); ?></dt>
            <dd><?php echo $this->formDate($dateDebut) . $this->formElementErrors($dateDebut); ?></dd>

            <dt><?php echo $this->formLabel($this->entryForm->get('DateEnd')); ?></dt>
            
            <dd><?php echo $this->formDate($this->entryForm->get('DateEnd')) . $this->formElementErrors($this->entryForm->get('DateEnd')); ?></dd>
            
            <dt><?php echo $this->formLabel($this->entryForm->get('comment')); ?></dt>
            
            <dd><?php echo $this->formTextarea($this->entryForm->get('comment')) . $this->formElementErrors($this->entryForm->get('comment')); ?></dd>

            <dd><?php echo $this->formSubmit($this->entryForm->get('submit')); ?></dd>
        </dl>
        <?php echo $this->form()->closeTag() ?>
        </section>
    </div>
</div>