<div id ='myModal' class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Ajouter une nouvelle demande de congé</h4>
      </div>
      <div class="modal-body">
        <?php
        $this->entryForm->setAttribute('action', $this->url('add-request', ['id' => $idEmployee]));
        $this->entryForm->setAttribute('method', 'post');
        $this->entryForm->prepare();
        echo $this->form()->openTag($this->entryForm) 
        ?>
        <table class='form-table'>
            <tr>
                <td><label><?php $dateDebut = $this->entryForm->get('DateDebut'); echo $this->formLabel($dateDebut); ?></label></td>
                <td><?php echo $this->formDate($dateDebut) . $this->formElementErrors($dateDebut); ?></td>
            </tr>
            <tr>
                 <td><label><?php echo $this->formLabel($this->entryForm->get('DateEnd')); ?></label></td>
                 <td><?php echo $this->formDate($this->entryForm->get('DateEnd')) . $this->formElementErrors($this->entryForm->get('DateEnd')); ?></td>
             </tr>
             <tr>
                <td><label><?php echo $this->formLabel($this->entryForm->get('comment')); ?></label></td>
                <td><?php echo $this->formTextarea($this->entryForm->get('comment')) . $this->formElementErrors($this->entryForm->get('comment')); ?></td>
            </tr>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <?php echo $this->formSubmit($this->entryForm->get('submit')); ?>
        <?= $this->form()->closeTag() ?>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
