<style>
table {
	width:700px;
}
th {
	color: #387FBC;
	background: #DEE3E8;
}
td, th {
	width : 300px;
	height :50px;
	border-bottom : 1px solid #ccc;
	text-align:center;
}
</style>
<div id="wrapper">
	<!-- end #header -->
	<div id="page">
	   <div style= 'width:1100px'>
    	   <div style = 'width:300px;position:relative;margin-right:50px; height:600px;float:left'>
    	       <center><h3>Liste des Employées</h3></center>
    	       <div class="list-group">
    	        <?php foreach ($employees as $employee):?>
	               <a href="<?= $this->url('employee', ['id' => $employee['id']])?>" class="list-group-item <?= ($employee['id'] != $id) ? :'active'?> "><?= $employee['name']?></a>
	            <?php endforeach;?>
                </div>
    	   </div>
    	   
	       <div style ='width:690px;position:relative; height:600px;float:left'>
	       <h3>Liste des congées</h3>
                <table>
                    <tHead>
                        <th>Date de debut</th>
                        <th>Date de fin</th>
                        <th>Commentaire</th>
                        <th>Action</th>
                    </tHead>
                    <?php if($leaveEmployee) :?>
                    <tBody>
                    <?php foreach ($leaveEmployee as $employee):?>
                        <tr> 
                            <td><?php $dateDebut = new DateTime($employee['start_date']);
                            echo $dateDebut->format('d/m/Y')?></td>
                            <td><?php $dateFin = new DateTime($employee['end_date']);
                            echo $dateFin->format('d/m/Y')?></td>
                            <td><?= $employee['comment'];?></td>
                            <td><?php if ($employee['status'] == Leave\Model\Leave::STATUS_PENDING) :?>
                                Demande en attente
                                <?php elseif ($employee['status'] == Leave\Model\Leave::STATUS_APPROVED) : ?>
                                Congé approuvé
                                <?php elseif ($employee['status'] == Leave\Model\Leave::STATUS_REFUSED) :?>
                                Congé refusé
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tBody>
                    <?php endif;?>
                </table>
            </div>
            
        </div>
    </div>
</div>