
<style>
table {
	width:1000px;
}
th {
	color: #387FBC;
	background: #DEE3E8;
}
td, th {
	height :50px;
	border-bottom : 1px solid #ccc;
	text-align:center;
}
</style>
<div id="wrapper">
	<!-- end #header -->
	<div id="page">
	<div class="btn-group">
	   <a href='<?=$this->url('employee')?>' class= 'btn btn-default'> Voir la list de tous les employées</a>
	</div>
	<BR><BR>
        <table>
            <tHead>
                <th>Employees</th>
                <th>Date de debut</th>
                <th>Date de fin</th>
                <th>Commentaire</th>
                <th>Action</th>
            </tHead>
            <tBody>
            <?php foreach ($employees as $employee):?>
                <tr> 
                    <td><?= $employee['name'];?></td>
                    <td><?php $dateDebut = new DateTime($employee['start_date']);
                    echo $dateDebut->format('d/m/Y')?></td>
                    <td><?php $dateFin = new DateTime($employee['end_date']);
                    echo $dateFin->format('d/m/Y')?></td>
                    <td><?= $employee['comment'];?></td>
                    <td><div class="btn-group">
                        <a href="<?= $this->url('validate-request' , ['id' => $employee['id']]); ?>" class= 'btn btn-success'> Valider </a>
                        <a href="<?= $this->url('refuse-request' , ['id' => $employee['id']]); ?>" class= 'btn btn-danger'> Refuser </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
            </tBody>
        </table>
    </div>
</div>