<style>
table {
	width:700px;
}
td, th {
	width : 300px;
	height :50px;
	border-bottom : 1px solid #ccc;
}
</style>
<div id="wrapper">
	<!-- end #header -->
	<div id="page">
	   <a href='<?=$this->url('employee')?>'> Voir la list de tous les employées</a>
        <table>
            <tHead>
                <th>Employees</th>
                <th>Date de debut</th>
                <th>Date de fin</th>
                <th>Commentaire</th>
                <th>Action</th>
            </tHead>
            <tBody>
            <?php foreach ($employees as $employee):?>
                <tr> 
                    <td><?= $employee['name'];?></td>
                    <td><?php $dateDebut = new DateTime($employee['start_date']);
                    echo $dateDebut->format('d/m/Y')?></td>
                    <td><?php $dateFin = new DateTime($employee['end_date']);
                    echo $dateFin->format('d/m/Y')?></td>
                    <td><?= $employee['comment'];?></td>
                    <td><a href="<?= $this->url('validate-request' , ['id' => $employee['id']]); ?>"> Valider </a><BR>
                        <a href="<?= $this->url('refuse-request' , ['id' => $employee['id']]); ?>"> Refuser </a>
                    </td>
                </tr>
            <?php endforeach;?>
            </tBody>
        </table>
    </div>
</div>