<style>
table {
	width:1000px;
}
th {
	color: #387FBC;
	background: #DEE3E8;
}
td, th {
	height :50px;
	border-bottom : 1px solid #ccc;
	text-align:center;
}
table.form-table td, table.form-table th{
	border-bottom : 0 !important;
	text-align:left !important;
}
</style>

<div id="wrapper">
	<!-- end #header -->
	<div id="page">
    	<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
            Ajouter une nouvelle demande
        </button>  
    	<BR><BR>
    	<table>
            <tHead>
                <th>Date Début</th>
                <th>Date fin</th>
                <th>Commentaire</th>
                <th>Statut</th>
            </tHead>
            <tBody>
            <?php foreach ($leaves as $leave):?>
                <tr> 
                    <td><?php $dateDebut = new DateTime($leave['start_date']);
                    echo $dateDebut->format('d/m/Y')?></td>
                    <td><?php $dateFin = new DateTime($leave['end_date']);
                    echo $dateFin->format('d/m/Y')?></td>
                    <td><?= $leave['comment']?></td>
                    <td><?php if ($leave['status'] == Leave\Model\Leave::STATUS_PENDING) :?>
                        Demande en attente
                        <?php elseif ($leave['status'] == Leave\Model\Leave::STATUS_APPROVED) : ?>
                        Congé approuvé
                        <?php elseif ($leave['status'] == Leave\Model\Leave::STATUS_REFUSED) :?>
                        Congé refusé
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;?>
            </tBody>
        </table>
	</div>
	<!-- end #page -->
</div>

<?= $this->partial('add-request.phtml');?>