<style>
table {
	width:1000px;
}
th {
	color: #387FBC;
	background: #DEE3E8;
}
td, th {
	height :50px;
	border-bottom : 1px solid #ccc;
	text-align:center;
}
</style>

<div id="wrapper">
	<!-- end #header -->
	<div id="page">
	    <div class="btn-group">
    	   <a href='<?= $this->url('add-request', ['id' => $idEmployee])?>' class= 'btn btn-default'> Créer une nouvelle demande</a>
    	</div>
    	<BR><BR>
    	<table>
            <tHead>
                <th>Date Début</th>
                <th>Date fin</th>
                <th>Commentaire</th>
                <th>Statut</th>
            </tHead>
            <tBody>
            <?php foreach ($leaves as $leave):?>
                <tr> 
                    <td><?php $dateDebut = new DateTime($leave['start_date']);
                    echo $dateDebut->format('d/m/Y')?></td>
                    <td><?php $dateFin = new DateTime($leave['end_date']);
                    echo $dateFin->format('d/m/Y')?></td>
                    <td><?= $leave['comment']?></td>
                    <td><?php if ($leave['status'] == Leave\Model\Leave::STATUS_PENDING) :?>
                        Demande en attente
                        <?php elseif ($leave['status'] == Leave\Model\Leave::STATUS_APPROVED) : ?>
                        Congé approuvé
                        <?php elseif ($leave['status'] == Leave\Model\Leave::STATUS_REFUSED) :?>
                        Congé refusé
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;?>
            </tBody>
        </table>
	</div>
	<!-- end #page -->
</div>
